### ISSUE TITLE
Tech service

### ISSUE THREAD

**Issue by EzraAmes** [banisoradrian/BAC#1]
Hello. 
I hope you are doing well.
My name is Ezra Ames and I found you on Github. 
I want to discuss something with you but when is convenient to communicate with you?

**Comment by banisoradrian** [comment]
Hello! Write to me and I will answer you when I have time :)

**Comment by EzraAmes** [comment]
Thanks for your reply. Can we discuss more on email or somewhere?

**Comment by banisoradrian** [comment]
Hello! Write to me and I will answer you when I have time :)
    you can write to me at banisor.adrian@yahoo.com or continue here, as you wish
